    export const suggestMePrompts = [
        'A tranquil meadow filled with blooming wildflowers and butterflies.',
        'A mysterious abandoned castle engulfed in thick fog.',
        'A futuristic cityscape with neon-lit buildings and sleek hovercrafts.',
        'A serene lakeside retreat with a wooden dock stretching into calm water.',
        'A magical forest glen illuminated by soft rays of sunlight.',
        'A bustling marketplace with colorful stalls and lively vendors.',
        'A charming cottage overlooking a roaring ocean.',
        'A tranquil Zen garden with serene ponds and stone lanterns.',
        'An otherworldly alien landscape with towering rock formations.',
        'A cozy winter cabin surrounded by snow-covered pine trees.',
        'A vibrant street mural depicting a story of love and unity.',
        'A peaceful riverside scene with a wooden rowboat on calm waters.',
        'A giraffe wearing a party hat and blowing out candles.',
        'A superhero squirrel saving acorns from a villainous crow.',
        'A cupcake with legs and arms dancing on a stage.',
        'A dinosaur riding a skateboard while eating ice cream.',
        'A magical wizard casting spells with colorful sparkles.',
        'A monkey juggling planets in outer space.',
        'A talking watermelon having a conversation with a lemon.',
        'A lively concert venue with a stage and bright lights.',
        'A tranquil lakeside campsite with a crackling campfire.',
        'A futuristic space station orbiting a distant planet.',
        'An enchanting winter wonderland with a frozen lake and ice sculptures.',
        'A picturesque coastal town with colorful houses and a harbor.',
        'A bustling city street during a rainy night with umbrellas.',
        'A ninja turtle eating pizza on top of a skyscraper.',
        'A magical rainbow unicorn sliding down a rainbow.',
        'A smiling sun with sunglasses and beach accessories.',
        'A monkey in a spacesuit exploring a distant planet.',
        'A panda riding a rainbow-colored bicycle.',
        'A grand opera house with ornate architecture and a performance underway.',
        'A cozy log cabin tucked away in a snowy forest.',
        'A bustling market square with bustling crowds and historic architecture.',
        'A majestic waterfall cascading down moss-covered rocks.',
        'A serene rooftop garden oasis with lush greenery.',
        'A vintage train station with steam locomotives and passengers.',
        'A penguin family having a picnic on an iceberg.',
        'A monkey riding a roller coaster with arms in the air.',
        'A teddy bear riding a skateboard down a ramp.',
        'A historic castle perched on a hilltop with panoramic views.',
        'A bustling city square with fountains and outdoor cafés.',
        'A majestic wildlife safari with elephants and giraffes in their natural habitat.',
        'A serene mountain lake reflecting snow-capped peaks.',
        'An idyllic countryside picnic with a checkered blanket and a wicker basket.',
        'A charming canal in Amsterdam with colorful houseboats and bicycles.',
        'A remote cabin in the woods surrounded by autumn foliage.',
        'A superhero rabbit leaping over tall buildings.',
        'A magical castle made of candy and chocolate.',
        'A friendly alien with multiple eyes and antennas.',
        'A cat and a dog high-fiving each other.',
        'A robot and a dinosaur building a sandcastle on the beach.',
        'A whimsical garden with floating lanterns and talking flowers.',
        'A floating island in the sky with waterfalls and lush vegetation.',
        'A happy sun wearing sunglasses and a big smile in a clear blue sky.',
        'A mischievous kitten playing with a ball of yarn.',
        'A cheerful rainbow stretching across a green meadow.',
        'A group of colorful balloons floating in the air.',
        'A cute panda munching on bamboo shoots.',
        'A friendly robot offering a bouquet of flowers.',
        'A cozy campfire with marshmallows roasting on sticks.',
        'A playful dolphin jumping out of the water.',
        'A bucket filled with vibrant seashells collected from the beach.',
        'A child\'s drawing of a friendly monster with a big grin.',
        'A cheerful smiley face made of colorful balloons.',
        'A playful puppy chasing its own tail.',
        'A slice of pizza topped with all your favorite ingredients.',
        'A cute and fluffy bunny hopping through a field of flowers.',
        'A bucket filled with melting ice cream on a hot summer day.',
        'A stack of colorful, oversized donuts with sprinkles.',
        'A group of happy children blowing bubbles in a sunny park.',
        'A vibrant rainbow-colored popsicle melting in the sun.',
        'A pair of silly sunglasses with wacky designs.',
        'A smiling sun wearing a cool pair of sunglasses in a clear blue sky.'
    ]